spring.application.name=backend

# LLM
llm.model.id=gemma-3-4b-it
llm.base.url=${CLOUD_RUN_URL}
llm.api.url=${llm.base.url}/v1beta/models/${llm.model.id}:generateContent?
llm.api.key=${API_KEY

# Firestore
spring.cloud.gcp.firestore.project-id=${PROJECT_ID}
spring.cloud.gcp.firestore.emulator.enabled=true
spring.cloud.gcp.firestore.host-port=localhost:8081